# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_date_time', models.DateTimeField(blank=True, null=True)),
                ('caption', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('job_description', models.CharField(max_length=300)),
                ('shift_hours', models.IntegerField(default=8)),
                ('date_of_hire', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SL', 'Sick Leave'), ('VL', 'Vacation Leave'), ('EL', 'Emergency Leave')], max_length=2)),
                ('reason', models.TextField()),
                ('date_of_leave', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeApplyingForLeave', to='almondapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='OffsetApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_offset', models.DateTimeField(blank=True, null=True)),
                ('date_time_requested', models.DateTimeField(default=django.utils.timezone.now)),
                ('hours_requested_for_offset', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeApplyingForOffset', to='almondapp.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='dailytimelog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeLog', to='almondapp.Employee'),
        ),
    ]
