# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almondapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offsetapplication',
            old_name='DateTimeOffsetted',
            new_name='DateTimeApplied',
        ),
        migrations.AddField(
            model_name='offsetapplication',
            name='HoursOffsetted',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
